/**
 * Renders a finished run as a self-contained Markdown document.
 *
 * This is what the "Export" button downloads: a single file containing the
 * report plus the full provenance trail (which agents ran, how long they took,
 * how many tokens they used, and whether a human intervened).
 */
export function runToMarkdown(run) {
  const lines = [];
  const push = (...items) => lines.push(...items);

  push(`# ${run.topic}`, "");
  push(
    `> Generated by the Multimodal Research Orchestrator on ` +
      `${new Date(run.finishedAt).toLocaleString()} using **${run.model}**` +
      `${run.mock ? " _(offline mock mode)_" : ""}.`,
    ""
  );

  push("## Report", "", run.report.trim(), "");

  push("## Review", "");
  push(
    `- **Status:** ${run.review.status === "approved" ? "✅ approved" : "⚠️ needs revision"}`,
    run.review.reason ? `- **Reason:** ${run.review.reason}` : null,
    `- **Revision rounds:** ${run.revisions ?? 0}`,
    run.hitRevisionLimit ? "- **Note:** stopped at the revision limit." : null,
    ""
  );

  push("## Plan", "");
  push(...run.plan.map((step) => `${/^\d/.test(step) ? "" : "- "}${step}`), "");

  if (run.vision) {
    push("## Image analysis", "", run.vision.trim(), "");
  }

  push("## Research findings", "", run.research.findings.trim(), "");

  const { stats, keywords, phrases } = run.research;
  push("### Evidence extracted by the text-analysis tool", "");
  push(
    `- **Words:** ${stats.words} · **Sentences:** ${stats.sentences} · ` +
      `**Avg words/sentence:** ${stats.avgWordsPerSentence}`,
    `- **Source:** ${run.research.usedReference ? "user-supplied reference text" : "the topic itself"}`
  );
  if (keywords?.length) {
    push(`- **Top keywords:** ${keywords.map((k) => `\`${k.word}\` ×${k.count}`).join(", ")}`);
  }
  if (phrases?.length) {
    push(`- **Recurring phrases:** ${phrases.map((p) => `"${p.phrase}" ×${p.count}`).join(", ")}`);
  }
  push("");

  push("## Execution metrics", "");
  push("| Agent | Calls | Duration | Tokens |", "| --- | ---: | ---: | ---: |");
  for (const [agent, m] of Object.entries(run.metrics.agents ?? {})) {
    push(`| ${agent} | ${m.calls} | ${formatMs(m.durationMs)} | ${m.tokens} |`);
  }
  push(
    "",
    `**Total:** ${formatMs(run.metrics.totalDurationMs)} · ` +
      `${run.metrics.usage.totalTokens} tokens ` +
      `(${run.metrics.usage.promptTokens} in / ${run.metrics.usage.outputTokens} out)` +
      (run.metrics.retries ? ` · ${run.metrics.retries} automatic retries` : ""),
    ""
  );

  return lines.filter((line) => line !== null).join("\n");
}

export function formatMs(ms) {
  if (!ms && ms !== 0) return "—";
  return ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} s`;
}

/** Filesystem-safe filename derived from the topic. */
export function suggestFilename(run) {
  const slug = run.topic
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50) || "report";
  return `${slug}.md`;
}
